import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stock App V1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-blue-600 text-white p-4">
          <div className="container mx-auto flex gap-6">
            <Link href="/" className="hover:text-blue-200">Home</Link>
            <Link href="/customer" className="hover:text-blue-200">Customer Management</Link>
          </div>
        </nav>
        {children}
        </body>
    </html>
  );
}
